### ISSUE TITLE
feat: add `src` route for all base smart contracts

### ISSUE THREAD

**Issue by luislucena16** [blockful-io/swaplace-contracts#158]
- the objective is to aggregate `src` to modularise the files in a hierarchical order.

@0xneves please assign this to me!

**Comment by 0xneves** [comment]
Yoo @luislucena16 

It's not much of a practice to create src folder following hardhat standards, as some features already have hardcoded paths to `test`, `scripts` and `contracts` folders.

I'll close this issue as it doesn't fit the current schedule.

**Comment by luislucena16** [comment]
hey @0xneves 
I understand what you are saying, I think I didn't explain myself very well! What I mean is to add `src` inside contracts, where there are different contracts but inside src are the main ones, for example:

All this inside contracts:
```
- contracts:
   src: Swaplace.sol, SwaplaceFactory.sol
   mock: SwaplaceMock.sol 
   examples: SwaplaceExamples.sol
   poc: SwaplacePoC.sol
```

for me it's more modular and clearer!
